
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: dikalinkirill/momo-backend:0.1
    ports:
      - "8081"
    environment:
      - TZ=UTC
    networks:
      - app_net
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: dikalinkirill/momo-frontend:0.1
    ports:
      - "8080"
    depends_on:
      - backend
    networks:
      - app_net
    volumes:
      - nginx_cache:/var/cache/nginx
      - nginx_logs:/var/log/nginx
    restart: unless-stopped

volumes:
  nginx_cache:
  nginx_logs:

networks:
  app_net:
